# This deploys to smoke.iam.forgeops.com.
# for self signed SSL certs. It is suitable for local minikube development
namespace: smoke
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../forgeops
