# This deploys to default.iam.example.com.
resources:
- ../all
- ../../../base/ig

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    AM_STORES_USER_SERVERS: "ds-idrepo-0.ds-idrepo:1389,ds-idrepo-1.ds-idrepo:1389"
    AM_STORES_CTS_SERVERS: "ds-cts-0.ds-cts:1389,ds-cts-1.ds-cts:1389"

- |-
  #Patch AM
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: am
  spec:
    template:
      spec:
        containers:
          - name: openam
            resources:
              requests:
                memory: 4Gi
                cpu: 2000m
              limits:
                memory: 5Gi
                cpu: 3000m
            imagePullPolicy: Always

- |-
  #Patch DS CTS
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-cts
  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: ds
            resources:
              requests:
                memory: 3Gi
                cpu: 2000m
              limits:
                memory: 5Gi
                cpu: 3000
        initContainers:
          - name: initialize
            imagePullPolicy: Always
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
        storageClassName: fast

- |-
  #Patch DS IDREPO
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-idrepo
  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: ds
            resources:
              requests:
                memory: 3Gi
                cpu: 2000m
              limits:
                memory: 5Gi
                cpu: 3000
        initContainers:
          - name: initialize
            imagePullPolicy: Always
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
        storageClassName: fast

- |-
  #Patch IDM
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: idm
  spec:
    replicas: 2
    template:
      spec:
        containers:
        - name: openidm
          resources:
            requests:
              memory: 4Gi
              cpu: 2000m
            limits:
              memory: 6Gi
              cpu: 3000m
          imagePullPolicy: Always

- |-
  #Patch IG
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ig
  spec:
    template:
      spec:
        containers:
          - name: ig
            imagePullPolicy: Always
