# Deploys to prod.iam.forgeops.com. Uses the Let's encrypt issuer for SSL.
namespace: fbc
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/am
  - ../../../base/idm
  - ../../../base/7.0/ingress
  - ../../../base/end-user-ui
  - ../../../base/login-ui
  - ../../../base/admin-ui
  - ../../../base/amster


patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    DOMAIN: "forgeops.com"

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: forgerock
  patch: |-
    - op: replace
      path: /metadata/annotations/certmanager.io~1cluster-issuer
      value: letsencrypt-prod
      # value: default-issuer  # Default