# Deploys to prod.iam.forgeops.com. Uses the Let's encrypt issuer for SSL.
# namespace: fbc
namespace: fbctest
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/am
  - ../../../base/7.0/ingress

configMapGenerator:
- name: platform-config
  # The env vars below can be passed into a pod using the envFrom pod spec.
  # These global variables can be used to parameterize your deployments.
  # The FQDN and URLs here should match your ingress or istio gateway definitions
  literals:
  - FQDN=$(NAMESPACE).iam.forgeops.com
  - SUBDOMAIN=iam
  - DOMAIN=forgeops.com
  - AM_URL=https://$(NAMESPACE).iam.forgeops.com/am
  - IDM_ADMIN_URL=https://$(NAMESPACE).iam.forgeops.com/admin
  - IDM_UPLOAD_URL=https://$(NAMESPACE).iam.forgeops.com/upload
  - IDM_EXPORT_URL=https://$(NAMESPACE).iam.forgeops.com/export
  - PLATFORM_ADMIN_URL=https://$(NAMESPACE).iam.forgeops.com/platform
  - IDM_REST_URL=https://$(NAMESPACE).iam.forgeops.com/openidm
  - ENDUSER_UI_URL=https://$(NAMESPACE).iam.forgeops.com/enduser
  - LOGIN_UI_URL=https://$(NAMESPACE).iam.forgeops.com/login/#/service/Login
  - ENDUSER_CLIENT_ID=endUserUIClient
  - ADMIN_CLIENT_ID=idmAdminClient
  - THEME=default
  # Additional FBC. TODO; Rationalize these
  - AM_SERVER_FQDN=$(NAMESPACE).iam.forgeops.com
<<<<<<< HEAD
  - AM_STORES_USER_SERVERS=ds-idrepo-0.ds-idrepo
  - AM_STORES_CTS_SERVERS=ds-cts-0.ds-cts
  - AM_STORES_APPLICATION_SERVERS=ds-idrepo-0.ds-idrepo
  - AM_STORES_POLICY_SERVERS=ds-idrepo-0.ds-idrepo
=======
  - AM_STORES_USER_SERVERS=ds-idrepo-0.ds-idrepo:1389
  - AM_STORES_CTS_SERVERS=ds-cts-0.ds-cts:1389
  - AM_STORES_POLICY_SERVERS=ds-idrepo-0.ds-idrepo:1389
  - AM_STORES_APPLICATION_SERVERS=ds-idrepo-0.ds-idrepo:1389
>>>>>>> 1d5af87f... feat: AM fbc

# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
- name: DOMAIN
  fieldref:
    fieldpath: data.DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
- name: SUBDOMAIN
  fieldref:
    fieldpath: data.SUBDOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
  fieldref:
    fieldpath: metadata.namespace
