# Deploys to prod.iam.forgeops.com. Uses the Let's encrypt issuer for SSL.
namespace: default
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/forgeops-secrets
  - ../../../base/am
  - ../../../base/amster
  - ../../../base/7.0/ds/cts
  - ../../../base/7.0/ds/idrepo
  - ../../../base/7.0/ingress