# This deploys to default.iam.example.com. It uses the ca-issuer
# for self signed SSL certs. It is suitable for local minikube development
namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../base/kustomizeConfig
- ../../../base/forgeops-secrets
- ../../../base/7.0/ds/cts
- ../../../base/7.0/ds/idrepo
- ../../../base/am
- ../../../base/amster
- ../../../base/idm
- ../../../base/end-user-ui
- ../../../base/login-ui
- ../../../base/admin-ui
- ../../../base/7.0/ingress
- ../../../base/ldif-importer

# By default we leave the Application out. You need an Application Controller to deploy this.
#- application.yaml
